Consts = {}

Consts.INT32_MAX = 2147483647
Consts.UINT16_MAX = 65535
Consts.UINT8_MAX = 255

Consts.MAX_HP = Consts.INT32_MAX + 1
Consts.MAX_MODULE_SLOTS = Consts.UINT16_MAX
Consts.MAX_COST_ITEM_COUNT = Consts.UINT16_MAX
Consts.MAX_UNDERGROUND_BELT_DISTANCE = Consts.UINT8_MAX
Consts.MAX_UNDERGROUND_PIPE_DISTANCE = Consts.UINT8_MAX
Consts.MAX_CHARGING_OFFSET_COUNT = Consts.UINT8_MAX
Consts.BELT_MAX_SPEED = math.pow(10, 9)
Consts.MAX_WIRE_DISTANCE = 64
Consts.MAX_SUPPLY_DISTANCE = 64
Consts.MAX_MOVEMENT_SLOW_DOWN_FACTOR = 1
Consts.MAX_FRICTION = 1

Consts.EMPTY_FUNCTION = function() end