require "consts"

require "functions.util"
require "functions.create-object"
require "functions.create-item"
require "functions.create-recipe"
require "functions.add-data"

require "prototypes.entity.enemy"

require "prototypes.entity.entities.assembler"
require "prototypes.entity.entities.belt"
require "prototypes.entity.entities.underground-belt"
require "prototypes.entity.entities.splitter"
require "prototypes.entity.entities.offshore-pump"
require "prototypes.entity.entities.long-handed-inserter"
require "prototypes.entity.entities.radar"
require "prototypes.entity.entities.lamp"
require "prototypes.entity.entities.wall"
require "prototypes.entity.entities.lab"
require "prototypes.entity.entities.furnace"
require "prototypes.entity.entities.big-electric-pole"
require "prototypes.entity.entities.substation"
require "prototypes.entity.entities.gate"
require "prototypes.entity.entities.steel-chest"
require "prototypes.entity.entities.logistic-chest-passive-provider"
require "prototypes.entity.entities.logistic-chest-active-provider"
require "prototypes.entity.entities.logistic-chest-storage"
require "prototypes.entity.entities.logistic-chest-buffer"
require "prototypes.entity.entities.logistic-chest-requester"
require "prototypes.entity.entities.solar-panel"
require "prototypes.entity.entities.accumulator"
require "prototypes.entity.entities.stack-inserter"
require "prototypes.entity.entities.stack-filter-inserter"
require "prototypes.entity.entities.land-mine"
require "prototypes.entity.entities.rocket-silo"
require "prototypes.entity.entities.roboport"
require "prototypes.entity.entities.storage-tank"
require "prototypes.entity.entities.pump"
require "prototypes.entity.entities.beacon"
require "prototypes.entity.entities.pipe"
require "prototypes.entity.entities.pipe-to-ground"
require "prototypes.entity.entities.pipe"
require "prototypes.entity.entities.chemical-plant"
require "prototypes.entity.entities.oil-refinery"
require "prototypes.entity.entities.centrifuge"

--TODO spider!
-- require "prototypes.entity.entities.reactor"
-- require "prototypes.entity.entities.heat-exchanger"
-- require "prototypes.entity.entities.steam-turbine"
-- require "prototypes.entity.entities.heat-pipe"


